# Qlty configuration for the Pulse TypeScript client
# See https://github.com/piksel/qlty for configuration details and options.

# Include patterns for formatting, linting, and test coverage
include = ["src/**/*.ts", "test/**/*.ts"]

[coverage]
# Minimum acceptable coverage thresholds (initially lowered until tests are ported)
lines = 0
branches = 0
functions = 0
statements = 0
