name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    merge_group:

permissions:
    contents: read
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install Qlty.io
              uses: qltysh/qlty-action/install@v1

            - name: Install dependencies
              run: bun install

            - name: Run Qlty checks
              run: bun run qlty:check

            - name: Build library
              run: bun run build

            - name: Generate coverage report
              run: bun run test -- --coverage
              env:
                  PULSE_CLIENT_ID: aiIu81CUdkVTeD0aS4GPzTX8n2Q5EDHS
                  PULSE_CLIENT_SECRET: ${{ secrets.PULSE_CLIENT_SECRET }}
                  PULSE_TOKEN_URL: https://wise-dev.eu.auth0.com/oauth/token
                  PULSE_AUDIENCE: https://dev.core.researchwiseai.com/pulse/v1
                  PULSE_BASE_URL: https://staging.pulse.researchwiseai.com/v1

            - name: Upload coverage to Qlty.sh
              uses: qltysh/qlty-action/coverage@v1
              with:
                  token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
                  files: coverage/lcov.info
