name: Release

on:
    push:
        tags:
            - 'v*.*.*'
    workflow_dispatch:

permissions:
    contents: write
    id-token: write
    actions: read

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install Qlty.io
              uses: qltysh/qlty-action/install@v1

            - name: Install dependencies
              run: bun install

            - name: Build library
              run: bun run build

            - name: Generate SBOM
              uses: anchore/sbom-action@v0
              with:
                  path: .
                  format: cyclonedx-xml
                  output-file: sbom.xml

            - name: Create package
              id: pack
              run: echo "FILE=$(npm pack)" >> $GITHUB_OUTPUT

            - name: Install Cosign
              uses: sigstore/cosign-installer@v3

            - name: Sign tarball
              run:
                  cosign sign-blob --yes --key "$COSIGN_PRIVATE_KEY" --output-signature "${{
                  steps.pack.outputs.FILE }}.sig" "${{ steps.pack.outputs.FILE }}"
              env:
                  COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

            - name: Publish to npm
              run: bun publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create GitHub release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      ${{ steps.pack.outputs.FILE }}
                      ${{ steps.pack.outputs.FILE }}.sig
                      sbom.xml
                      cosign.pub
                  body_path: CHANGELOG.md
